name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Nuxt application
        run: yarn build

      - name: Package Electron app
        run: yarn electron:make

      - name: Upload Electron artifact
        uses: actions/upload-artifact@v4
        with:
          name: vista-electron
          path: release/
          if-no-files-found: error
